//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCRUD.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICRUDClientService")]
    public interface ICRUDClientService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/CreateClient", ReplyAction="http://tempuri.org/ICRUDClientService/CreateClientResponse")]
        bool CreateClient(Business.ClientCredentials client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/CreateClient", ReplyAction="http://tempuri.org/ICRUDClientService/CreateClientResponse")]
        System.Threading.Tasks.Task<bool> CreateClientAsync(Business.ClientCredentials client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/UpdateClient", ReplyAction="http://tempuri.org/ICRUDClientService/UpdateClientResponse")]
        bool UpdateClient(Business.ClientCredentials old, Business.ClientCredentials newC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/UpdateClient", ReplyAction="http://tempuri.org/ICRUDClientService/UpdateClientResponse")]
        System.Threading.Tasks.Task<bool> UpdateClientAsync(Business.ClientCredentials old, Business.ClientCredentials newC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/DeleteClient", ReplyAction="http://tempuri.org/ICRUDClientService/DeleteClientResponse")]
        bool DeleteClient(Business.ClientCredentials client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/DeleteClient", ReplyAction="http://tempuri.org/ICRUDClientService/DeleteClientResponse")]
        System.Threading.Tasks.Task<bool> DeleteClientAsync(Business.ClientCredentials client);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/GetClients", ReplyAction="http://tempuri.org/ICRUDClientService/GetClientsResponse")]
        Business.ClientCredentials[] GetClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRUDClientService/GetClients", ReplyAction="http://tempuri.org/ICRUDClientService/GetClientsResponse")]
        System.Threading.Tasks.Task<Business.ClientCredentials[]> GetClientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRUDClientServiceChannel : ClientCRUD.ServiceReference1.ICRUDClientService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRUDClientServiceClient : System.ServiceModel.ClientBase<ClientCRUD.ServiceReference1.ICRUDClientService>, ClientCRUD.ServiceReference1.ICRUDClientService {
        
        public CRUDClientServiceClient() {
        }
        
        public CRUDClientServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRUDClientServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDClientServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRUDClientServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CreateClient(Business.ClientCredentials client) {
            return base.Channel.CreateClient(client);
        }
        
        public System.Threading.Tasks.Task<bool> CreateClientAsync(Business.ClientCredentials client) {
            return base.Channel.CreateClientAsync(client);
        }
        
        public bool UpdateClient(Business.ClientCredentials old, Business.ClientCredentials newC) {
            return base.Channel.UpdateClient(old, newC);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateClientAsync(Business.ClientCredentials old, Business.ClientCredentials newC) {
            return base.Channel.UpdateClientAsync(old, newC);
        }
        
        public bool DeleteClient(Business.ClientCredentials client) {
            return base.Channel.DeleteClient(client);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteClientAsync(Business.ClientCredentials client) {
            return base.Channel.DeleteClientAsync(client);
        }
        
        public Business.ClientCredentials[] GetClients() {
            return base.Channel.GetClients();
        }
        
        public System.Threading.Tasks.Task<Business.ClientCredentials[]> GetClientsAsync() {
            return base.Channel.GetClientsAsync();
        }
    }
}
